### ISSUE TITLE
Do we need pooling between convolution and linear layers?

### ISSUE THREAD

**Issue by bcpenggh** [2017-fall-DL-training-program/ConvNetwork#10]
Hi TA,
In the lab yesterday, TA mentioned we should pay attention to match the output dimension of last convolution layer with the input dimension of the linear layer. Does that imply there is no pooling between the two layers? In the example code the pooling is used. Thanks for your reply.

**Comment by JiaRenChang** [comment]
Hi,
There is a global average pooling between last convolution layer and linear layer in our homework.
Jia-Ren

**Comment by bcpenggh** [comment]
Hi Jia-Ren,

If the output channels of last convolution layer is equal to the input of the linear layer, does that imply the pooling decimate the "8x8" image to a single point?

The flow is shown below. It seems weird to decimate the image to a single point. Do I understand correctly?
Last basic block: 16x16x32 --> 8x8x64
Pooling: 8x8x64 --> KxKx64
Linear input: 64 --> 10
==> "K" of pooling must be 1 to connect to the next linear layer, but the image becomes a single pint

Regards,
BC

**Comment by bcpenggh** [comment]
Hi Jia-Ren,

If the output channels of last convolution layer is equal to the input of the linear layer, does that imply the pooling decimate the "8x8" image to a single point?

The flow is shown below. It seems weird to decimate the image to a single point. Do I understand correctly?
Last basic block: 16x16x32 --> 8x8x64
Pooling: 8x8x64 --> KxKx64
Linear: 64 --> 10
==> "K" of pooling must be 1 to connect to the next linear layer, but the image becomes a single pint

Regards,
BC

**Comment by bcpenggh** [comment]
Hi Jia-Ren,

If the output channels of last convolution layer is equal to the input of the linear layer, does that imply the pooling decimate the "8x8" image to a single point?

The flow is shown below. It seems weird to decimate the image to a single point. Do I understand correctly?
Last basic block: 16x16x32 --> 8x8x64
Pooling: 8x8x64 --> KxKx64
Linear: 64 --> 10
==> "K" of pooling must be 1 to connect to the next linear layer, but the image becomes a single point

Regards,
BC

**Comment by JiaRenChang** [comment]
Hi,
So it named **global** average pooling.
It means that it averages 8x8 feature map into 1x1.

Jia-Ren
