### ISSUE TITLE
Why the mini-batch sizes of training and testing are different?

### ISSUE THREAD

**Issue by bcpenggh** [2017-fall-DL-training-program/ConvNetwork#11]
Dear TA,

In the example code, the mini-batch size of training and testing are 128 and 100 respectively. Is there any reason to choose these numbers? I understand 128 "seems" reasonable. But why should we choose a slightly smaller number "100" for testing? Thanks for your advice.

Regards,
BC

**Comment by JiaRenChang** [comment]
Hi,
You can use any number of batch size during testing.
Jia-Ren
