### ISSUE TITLE
Could we use Bottleneck to achieve 50 layers network even 110 layers network?

### ISSUE THREAD

**Issue by fansia** [2017-fall-DL-training-program/ConvNetwork#9]
If my understanding is right, each Residual basic block contains 2 layers and each bottleneck block contain 3 layers.  Assume, we are going to build 50 layers 
* Use Basic Block
=> (56 -2) / 2 = 27 --> need 27 basic blocks
* Use Bottleneck Block
=> (56-2) / 3 = 24  --> need 24 bottleneck blocks

Thank you.

**Comment by JiaRenChang** [comment]
Hi,
   Yes, it's right.
Jia-Ren
